#!/bin/env python3

import os
import sys
import subprocess

from urllib.parse import urlparse

url = sys.argv[1]
parsed_url = urlparse(sys.argv[1])

clone_path = f'/home/jlebon/Code/{parsed_url.netloc}{parsed_url.path}'
clone_path = clone_path.rstrip('/')
clone_path = clone_path.removesuffix('.git')

if os.path.isdir(clone_path):
    raise Exception(f"{clone_path} already exists")

subprocess.check_call(['git', 'clone', '-o', 'upstream', url, clone_path])
print(clone_path)
