#!/bin/bash
set -euo pipefail

echo "Resetting podman storage"
podman rm --all -f
podman rmi --all -f
podman system reset -f

echo "Pulling latest pet image"
podman pull quay.io/jlebon/pet

echo "Creating pet container"
toolbox create --image quay.io/jlebon/pet

# XXX until we move to f44; so that we have adaptive theme support
toolbox run -c pet sudo dnf install -y /var/home/jlebon/Code/src.fedoraproject.org/rpms/tmux/x86_64/tmux-3.6a-1.fc43.x86_64.rpm

toolbox run -c pet tmux new-session -d

# Code may try to resolve the default 'toolbox' hostname for real, which makes
# no sense at all. Just force it to be localhost. Ideally, toolbox would allow
# overriding this.
# Hit this in cosa where the flock code wants to resolve hostnames in the
# process of trying to make NFS-safe locks... Should fix that.
toolbox run -c pet sudo bash -c 'echo localhost > /etc/hostname'
toolbox run -c pet sudo hostname localhost
