#!/bin/bash
set -euo pipefail

# Get the source forge permalink to the given file and optional line number.
# It can be used from Vim by defining a command that passes the filename and
# line number. E.g.:
#
#   command GitPermaLink execute ":!git permalink %:p " . line(".")

main() {
    local mode
    mode=$(basename "$0")

    case "${mode}" in
        git-permalink) permalink "$@";;
        git-commitlink) commitlink "$@";;
        *) echo "Unknown mode: $mode" >&2; exit 1;;
    esac
}

permalink() {
    if [ $# -lt 1 ]; then
        echo "Usage: git permalink <FILE> [LINENO]" >&2
        exit 1
    fi

    local file=$1; shift
    local lineno=${1:-}

    # make sure it's absolute
    file=$(realpath "${file}")

    cd "$(dirname "${file}")"
    file=$(make_relative_to_git_repo "${file}")

    local rev
    rev=$(git rev-parse HEAD)

    local remote_url base repo
    remote_url=$(get_remote_url)
    base=$(parse_base "${remote_url}")
    repo=$(parse_repo "${remote_url}")

    if [[ $base == *pagure* ]] || [[ $base == *fedoraproject.org* ]]; then
        file="f/${file}"
    fi

    blob="blob/${rev}"
    if [[ $base == git.kernel.org ]]; then
        blob=tree
        file="${file}?id=${rev}"
    fi

    if [ -n "$lineno" ]; then
        if [[ $base == git.kernel.org ]]; then
            lineno="#n${lineno}"
        else
            lineno="#L${lineno}"
        fi
    fi

    echo "https://${base}/${repo}/${blob}/${file}${lineno}"
}

commitlink() {
    local rev=${1:-HEAD}
    rev=$(git rev-parse "${rev}")

    local remote_url base repo
    remote_url=$(get_remote_url)
    base=$(parse_base "${remote_url}")
    repo=$(parse_repo "${remote_url}")

    if [[ $base == *pagure* ]] || [[ $base == *fedoraproject.org* ]]; then
        rev="c/${rev}"
    elif [[ $base == git.kernel.org ]]; then
        rev="commit/?id=${rev}"
    elif [[ $base == pkgs.devel.redhat.com ]]; then
        base="${base}/cgit"
        rev="commit/?id=${rev}"
    else
        rev="commit/${rev}"
    fi

    echo "https://${base}/${repo}/${rev}"
}

make_relative_to_git_repo() {
    local abspath=$1; shift
    local parent_dir
    parent_dir=$(dirname "${abspath}")
    local git_dir
    git_dir=$(cd "${parent_dir}" && git rev-parse --show-toplevel)

    echo "${abspath#"${git_dir}/"}"
}

get_remote_url() {
    local remote url
    remote=$(find_remote)
    git ls-remote --get-url "${remote}"
}

find_remote() {
    # prefer 'upstream' over 'origin'
    remotes=$(git remote)
    for remote in upstream origin; do
        if grep -q $remote <<< "$remotes"; then
            echo $remote
            return
        fi
    done
    return 1
}

parse_repo() {
    local url=$1; shift

    if [[ $url == ssh://*@*/* ]]; then
        local repo=${url#ssh://*@*/}
    elif [[ $url == git@*:* ]]; then
        local repo=${url#*:}
    elif [[ $url == https://*/* ]]; then
        local repo=${url#https://*/}
    else
        echo "ERROR: Unknown URL $url" >&2
        exit 1
    fi

    if [[ $url != https://git.kernel.org/* ]]; then
        repo=${repo%.git}
    fi
    echo "${repo}"
}

parse_base() {
    local url=$1; shift

    if [[ $url == ssh://*@*/* ]]; then
        local base=${url#ssh://*@}
        base=${base%%/*}
    elif [[ $url == git@*:* ]]; then
        local base=${url#git@}
        base=${base%:*}
        case "$base" in
            gitlab-rh) base=gitlab.com;;
            *);;
        esac
    elif [[ $url == https://*/* ]]; then
        local base=${url#https://}
        base=${base%%/*}
    else
        echo "ERROR: Unknown URL $url" >&2
        exit 1
    fi

    echo "${base}" >&2
    echo "${base}"
}

main "$@"
